#!/usr/bin/env ruby

BIN="o-saft"

require "pp"

class String
	def shell_escape
		self.gsub("'",'\'').gsub("\"",'\"').gsub('`','\`')
	end
end

options = [["",""]]
`#{BIN} --help=options`.each_line{|l|
	if l =~ /^[^\s]/
		options << []
		options.last << l.scan(/^(\-.*)/).flatten[0]
		options.last << ""
	else
		options.last[1] += l
	end
}

options.each{|o| o[1].strip!}
options.uniq!
options.delete(["",""])
options.delete([nil,""])

simopts = []
options.collect!{|o|
	if o[0] =~ /, /
		o[0].split(",").collect{|e|e.strip}.each{|e| simopts << [e,o[1]]}
		nil
	else
		o
	end
}
options += simopts
options.delete(nil)
options.collect!{|o|
	if o[0] =~ / / # cannot use options with spaces inside
		nil
	else
		o
	end
}
options += simopts
options.delete(nil)
options.each{|o,d|
	if o
		case o
		when /^--/
			opt = "l"
		#when /^-\w\w/ # old-style options
			#opt = "o"
		when /^-\w$/
			opt = "s"
		else
			opt = nil #unknown
		end
		if opt
			print "complete -f -c #{BIN} -#{opt} '#{o.gsub(/^-*/,"")}'"
			print " --description \"#{d[0..20].shell_escape}\"" if d != ""
			puts
		end
	end
}


commands = `#{BIN} --help=commands`.to_a.collect{|l|
	l.strip.scan(/^(\+[^\s]*)\s*(.*)$/).flatten
}.uniq
commands.each{|c,d|
	if c
		print "complete -f -c #{BIN} -a '#{c}'"
		print " --description \"#{d[0..20].shell_escape}\"" if d != ""
		puts
	end
}
