#!/bin/sh
#?
#? NAME
#?      o-saft_bench  - simple time and memory test program for o-saft.pl
#? SYNOPSYS
#?      o-saft_bench [target host]
#? DESCRIPTION
#?      Runs o-saft.pl with most common commands and measures execution and
#?      memory usage using system's  time  command.
#?      Results are appended to  o-saft_bench.times .
#?      localhost is used as target for testing, can be passed as parameter. 
#?

  SID="@(#) o-saft_bench 1.8 16/01/09 23:59:01"


  ich=${0##*/}
yeast=o-saft.pl
yeast=./yeast.pl
 host=localhost
 time=/usr/bin/time
  out=./${ich}.times
  cnt=4   # additional 4 lines which are the table header and footer line

[ $# -gt 0 ] && host="$1"

(echo
 echo -n "# " && date
 echo -n "# o-saft.pl +VERSION: " && $yeast +VERSION --norc
 echo -n "# System (uname -a):  " && uname -a
 echo -n "# Perl   (perl -v):   " && perl -v|grep This
 echo    "#"
) | tee -a $out
echo -n "# prepare ... "
$yeast +check localhost --trace --user >/dev/null 2>&1 # dummy to load modules and alocate memory
echo "done."
t="%U  %S  %E  %P  %Kk  %Mk"
line="#--------------------------------------+-----+------+-------+----+----+--------"
(
echo "#                                      |       time         |    |  memory    |"
echo "#         command                      | user system    real| CPU| av.  max   |"
echo $line
) >> $out
while read -r cmd ; do
	[ -z "$cmd" ] && continue  # skip final emtpy line
	#dbx# echo    "o-saft.pl $cmd "
	echo -n "o-saft.pl $cmd " | tee -a $out && $time --quiet -o $out -a -f "$t" $yeast $cmd >/dev/null && echo ""
        cnt=`expr $cnt + 1`
done << EoT
	+VERSION           --norc    \ 
	+version                     \ 
	+version --v --usr           \ 
	+version           --norc    \ 
	+version --v       --norc    \ 
	+libversion                  \ 
	+libversion        --norc    \ 
	+ciphers                     \ 
	+ciphers -V                  \ 
	+list                        \ 
	--v +help                    \ 
        --help=gen-wiki              \ 
        --help=gen-wiki --no-header  \ 
	+cipher               $host \ 
	+cipherall            $host \ 
	+info                 $host \ 
	+info  --noopenssl    $host \ 
	+quick                $host \ 
	+quick --noopenssl    $host \ 
	+check                $host \ 
	+check --noopenssl    $host \ 
	+quit  --trace-cmd --trace-time \ 
	+sizes                $host \ 
	+sizes --trace-cmd --trace-time $host \ 

EoT
# tricky here document:
# We want to have well formated texts (command and options) for o-saft.pl call.
# Hence we use a trailing backslash followed by a single space.

echo $line  >> $out
tail -$cnt $out
exit

#=============================================================================#
#== output should look like                                                 ==#

# Mi 23. Jul 23:42:11 MEST 2014
# o-saft.pl +VERSION: 14.07.25
# System (uname -a):  Linux circe 2.6.38-16-generic #66-heureca x86_64 x86_64 x86_64 GNU/Linux
# Perl   (perl -v):   This is perl, v5.10.1 (*) built for x86_64-linux-gnu-thread-multi
#
#                                      |       time         |    |  memory    |
#         command                      | user system    real| CPU| av.  max   |
#--------------------------------------+-----+------+-------+----+----+--------
o-saft.pl +VERSION           --norc    \ 2.63  0.86  0:03.50  99%  0k  6239184k
o-saft.pl +version                     \ 2.49  1.20  0:03.72  99%  0k  6248544k
o-saft.pl +version --v --usr           \ 2.79  0.94  0:03.78  98%  0k  6250304k
o-saft.pl +version           --norc    \ 2.60  1.10  0:03.74  98%  0k  6248416k
o-saft.pl +version --v       --norc    \ 2.64  1.07  0:03.74  99%  0k  6249344k
o-saft.pl +libversion                  \ 2.56  1.13  0:03.72  99%  0k  6243664k
o-saft.pl +libversion        --norc    \ 2.76  0.94  0:03.74  98%  0k  6243520k
o-saft.pl +ciphers                     \ 2.78  0.73  0:03.53  99%  0k  6243680k
o-saft.pl +ciphers -V                  \ 2.83  0.89  0:03.74  99%  0k  6243648k
o-saft.pl +list                        \ 2.70  0.82  0:03.54  99%  0k  6243680k
o-saft.pl --v +help                    \ 2.62  0.90  0:03.53  99%  0k  6240464k
o-saft.pl +gen-wiki                    \ 2.72  0.81  0:03.74  94%  0k  6245056k
o-saft.pl +gen-wiki    --usr           \ 2.52  0.97  0:03.51  99%  0k  6240336k
o-saft.pl +cipher            localhost \ 3.10  2.13  0:06.01  86%  0k  6258048k
o-saft.pl +cipherall         localhost \ 2.97  0.88  0:04.23  90%  0k  6251248k
o-saft.pl +info              localhost \ 2.77  1.95  0:04.96  94%  0k  6253888k
o-saft.pl +info  --noopenssl localhost \ 2.77  0.78  0:03.64  97%  0k  6253136k
o-saft.pl +quick             localhost \ 3.06  2.15  0:06.02  86%  0k  6259936k
o-saft.pl +quick --noopenssl localhost \ 3.17  0.90  0:04.74  85%  0k  6259168k
o-saft.pl +check             localhost \ 3.22  2.06  0:06.09  86%  0k  6260160k
o-saft.pl +check --noopenssl localhost \ 3.25  1.02  0:04.97  85%  0k  6259616k
#-------------------------------------+----+------+-------+----+----+----------

