#!/bin/sh
#?
#? NAME
#?      $0 - simple wrapper to call  o-saft.pl
#?
#? SYNOPSIS
#?      $0 [options] target
#?
#? DESCRIPTION
#?      Calls  o-saft.pl  with all specified arguments.  o-saft.pl's  output is
#?      then piped to the command specified in the  -post=  option.
#?      Command given with  -post=  must be located in  contrib/  directory  or
#?      must be found via  PATH  environment variable.
#?
#? OPTIONS
#?      -h      got it
#?      -list   list available programs in ./contrib/ directory
#?      -post="command [options]"
#?              command to pipe output of  o-saft.pl  too
#?
#? LIMITATIONS
#?      Option  -h  or  -list  or  -post=  must preceed all other options.
#?
#? EXAMPLES
#?	    $0 +cmd --option target
#?	    $0 -post='bunt.pl'      ' +cmd --option target
#?	    $0 -post='bunt.pl -blind' +cmd --option target
#?
# 
# Hacker's INFO
#       Uses options  -h  and  -post=  and not  --h  or  --help  or  --post  to
#       avoid conflicts with same option for  o-saft.pl .
#
#? VERSION
#?      @(#) o-saft 1.2 18/01/23 23:03:38
#?
#? AUTHOR
#?      17-dec-17 Achim Hoffmann
#?
# -----------------------------------------------------------------------------

ich=${0##*/}
dir=${0%/*};    [ "$dir" = "$0" ] && dir="."    # $0 found via $PATH in .
prg=o-saft.pl
post="cat";     # default, avoids special handling if -post= missing
contrib=$dir/contrib

case "$1" in
    -h  | '-?')
        \sed -ne "s/\$0/$ich/g" -e '/^#?/s/#?//p' $0
        \cat <<EoT
 NOTE
    To get help for  o-saft.pl, please use:
        $0 --help
    or
        o-saft.pl --help

EoT
        exit 0
        ;;
    -list)
        for exe in $contrib/* ; do
            [ -d "$exe" ] && continue
            [ -x "$exe" ] && echo "$exe"
        done
        exit 0
        ;;
    -post=*)
        post="`expr "$1" ':' '-post=\(.*\)'`"
        cmd=`echo "$post" | awk '{print $1}'`   # remove additional trailing arguments
        [ -x "$contrib/$cmd" ] && post="$contrib/$cmd"
        shift
        ;;
esac
#dbx# echo "#$post#"

$prg $@ | $post
exit 0
